---
abstract: 'All the Pinto components in one shot'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Pinto
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Task::Pinto:
    file: lib/Task/Pinto.pm
    version: 0.001
requires:
  App::Pinto::Admin: 0
  App::Pinto::Remote: 0
  Dist::Zilla::Plugin::Pinto::Add: 0
  Pinto: 0
  Pinto::Remote: 0
  Pinto::Server: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/thaljef/Task-Pinto/issues
  repository: git://github.com/thaljef/Task-Pinto.git
version: 0.001
